### ISSUE TITLE
[1.20.] Breaks Great Spells

### ISSUE THREAD

**Issue by DarianLStephens** [walksanatora/hexxy-dimensions#22]
With this mod added, Great Spells of any kind act as normal spells.
You can cast them immediately without problems. This is actually a very big issue because it completely breaks Hex progression. You can't become enlightened, and you can't unlock the entries for circles and stuff.

**Comment by walksanatora** [comment]
try again with latest on modrinth. I could have sworn I fixed this issue in hexxytest s1

**Comment by DarianLStephens** [comment]
I don't see any new version. I'm already running the latest 1.20.1 version (1.3.0) off Modrinth.

**Comment by Wolverine-14** [comment]
There was a version bump for 1.19.2 to 1.4.0 that hasn't made it's way to 1.20.1 yet. I just tested version 1.4.0, which is still only on 1.19.2, and the issue was fixed but in version 1.3.0, which is the latest version available for 1.20.1 on modrinth, this is still broken.
If it's possible please release 1.4.0 for minecraft1.20.1

**Comment by Wolverine-14** [comment]
Also as I stated in [this issue](https://github.com/walksanatora/hexxy-dimensions/issues/19) this is not a bug in version 1.1.1 even in minecraft 1.20.1
I tried the latest Artifact build from commit 513e2f8 but it still appears to be bugged in that build so the fix was done in one of the following commits for 1.19.2 backport
[back to the future](https://github.com/walksanatora/hexxy-dimensions/commit/0910b7addc6b76a8a30190998540e9cae39cf6c6)
[hexdoc fix?](https://github.com/walksanatora/hexxy-dimensions/commit/7396aadf0af1d06926a3fbbed1acbc911ab987c4)
[why book no work angy](https://github.com/walksanatora/hexxy-dimensions/commit/4a5ac215a7e857c93d31adf2c91fb7bde46364a7)
my guess is the first one due to how much was changed in that commit but I don't have enough knowledge on the code base to find the line or lines of code that fixes the issue. maybe I'll do a little more digging to find the fix and see if I can make a pull request if I do

**Comment by krypton1101** [comment]
Unfortunately, fix appeared as a side effect of porting to an older and simpler version of hexcasting on 1.19.
